import {createFileRoute} from '@tanstack/react-router';
import {useState,type FormEvent} from 'react';
import {ArrowRight,Copy,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {meta} from '@/lib/flavors';
import {RainbowHead} from '@/components/rainbow-head';
import {Doodle} from '@/components/doodle';
export const Route=createFileRoute('/pages/contact')({head:()=>meta('Say hello','Good questions, big ideas or just a little hello. Get in touch with the FIZZDAY crew.'),component:Contact});
function Contact(){const [prepared,setPrepared]=useState('');const [copied,setCopied]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setPrepared(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}`)}return <section className="utility-page"><RainbowHead as="h1" text="SAY HELLO" rainbow className="page-title"/><div className="contact-layout"><div className="contact-copy"><p>A burning question? A big idea? A really good joke? We’re all ears.</p><Doodle kind="hand"/><p className="product-note">Our official contact email is awaiting confirmation. Messages can be prepared here, but are not sent yet.</p></div><form className="contact-form" onSubmit={submit}>{prepared?<div className="success-state"><Doodle kind="spark"/><h2>LOOKING GOOD!</h2><p>Your message is prepared, not sent. The contact destination still needs to be added.</p><Button variant="sticker" className="mt-6" onClick={async()=>{await navigator.clipboard.writeText(prepared);setCopied(true)}} type="button">{copied?<Check/>:<Copy/>}{copied?'Message copied':'Copy your message'}</Button><Button variant="nav" className="mt-6" type="button" onClick={()=>{setPrepared('');setCopied(false)}}>Write another</Button></div>:<><div className="field"><label htmlFor="name">Your name</label><input id="name" name="name" placeholder="The name your friends use" required autoComplete="name"/></div><div className="field"><label htmlFor="email">Your email</label><input id="email" name="email" type="email" placeholder="you@somewhere.good" required autoComplete="email"/></div><div className="field"><label htmlFor="message">Spill the tea</label><textarea id="message" name="message" placeholder="We’re listening…" required/></div><Button variant="coral" type="submit">Prepare your hello<ArrowRight/></Button></>}</form></div></section>}
