import {createFileRoute,Link} from '@tanstack/react-router';
import {ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {meta,leaves,picnic} from '@/lib/flavors';
import {RainbowHead} from '@/components/rainbow-head';
import {Doodle} from '@/components/doodle';
import {Benefits,Marquee} from '@/components/shop-parts';
export const Route=createFileRoute('/pages/story')({head:()=>meta('A leaf less ordinary','Meet the leaf behind FIZZDAY: a little yerba tea, a lot of curiosity, and a colorful approach to everyday moments.'),component:Story});
function Story(){return <><section className="story-hero"><img src={leaves} alt="Sunlit fresh yerba mate leaves and citrus" width={1600} height={1008}/><RainbowHead as="h1" text="A LEAF LESS ORDINARY"/><span className="eyebrow">SMALL LEAF. BIG PERSONALITY.</span></section><Marquee/><section className="section"><RainbowHead text="LET’S SPILL THE TEA" className="section-title"/><div className="story-columns"><h3>IT STARTS WITH<br/>A LITTLE LEAF.<br/>AND A BIG IDEA.</h3><img src={leaves} alt="A closer look at green yerba leaves" width={800} height={600} loading="lazy"/><Doodle kind="leaf"/></div><p className="story-paragraph">Yerba mate has a story long before our little can. Traditionally shared as a tea in South America, it’s a leaf with a rich history. FIZZDAY is our colorful invitation to get curious, take a sip, and make a little more of your everyday.</p></section><section className="section pb-0"><RainbowHead text="GOOD STUFF ONLY" rainbow className="section-title"/></section><Benefits/><section className="section"><div className="process-grid"><img src={picnic} alt="Sharing bright drinks during a sunny day outdoors" width={1200} height={912} loading="lazy"/><div><h2>FROM LEAF<br/>TO LITTLE JOYS.</h2><p>We’re here for the long lunches, the unexpected detours, and the friends who say “one more game.” The ingredient sourcing and brewing details are awaiting confirmation. The good-time attitude? Already here.</p><Button variant="ink" asChild><Link to="/pages/faq">Still curious?<ArrowRight/></Link></Button></div></div></section></>}
