import {createFileRoute,Link} from '@tanstack/react-router';
import {ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {meta,flavors,faqGroups} from '@/lib/flavors';
import {RainbowHead} from '@/components/rainbow-head';
import {Doodle} from '@/components/doodle';
import {ProductGrid,Accordion} from '@/components/shop-parts';
export const Route=createFileRoute('/pages/subscription')({head:()=>meta('The regulars club','Make your favorite FIZZDAY flavor a regular thing. Explore the subscription club and choose your colorful crew.'),component:Subscription});
function Subscription(){return <><section className="subscription-hero"><RainbowHead as="h1" text="NEVER RUN DRY"/><p>Your favorites. On repeat. A little less fridge admin, a little more living.</p><p className="product-note">Subscription pricing, savings and delivery intervals to be confirmed.</p></section><section className="steps">{[['flower','01. Pick your personality','Find your favorite flavor. Or let your taste buds wander.'],['cloud','02. Make room for fizz','Your delivery schedule will be confirmed before subscriptions open.'],['spark','03. Join the regulars','Subscription savings and flexibility terms are coming soon.']].map(([icon,title,text])=><article key={title}><Doodle kind={icon}/><h2>{title}</h2><p>{text}</p></article>)}</section><section className="section products-section"><h2>Choose your regular crew</h2><ProductGrid subscription all={false}/></section><div className="video-collage" aria-label="Floating colorful FIZZDAY cans"><Doodle kind="spark"/>{flavors.slice(0,4).map(f=><img src={f.image} alt={f.name} width={180} height={500} loading="lazy" key={f.slug}/>)}<Doodle kind="flower"/></div><section className="section"><RainbowHead text="A FEW LITTLE QUESTIONS" className="section-title"/><div className="faq-list">{faqGroups[2].items.slice(0,4).map(([q,a])=><Accordion question={q} answer={a} key={q}/>)}</div><div className="center mt-10"><Button variant="ink" asChild><Link to="/pages/faq">All your questions<ArrowRight/></Link></Button></div></section></>}
