import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {ArrowUp,RotateCcw,Play} from 'lucide-react';
export function Runner(){
 const canvas=useRef<HTMLCanvasElement>(null);const action=useRef<()=>void>(()=>{});const [status,setStatus]=useState<'ready'|'playing'|'over'>('ready');const [score,setScore]=useState(0);
 useEffect(()=>{
 const c=canvas.current; const ctx=c?.getContext('2d');if(!c||!ctx)return;
 const css=getComputedStyle(document.documentElement);const color=(name:string)=>css.getPropertyValue(name).trim();const ink=color('--ink'),navy=color('--navy'),sky=color('--sky'),red=color('--coral'),yellow=color('--sun'),cream=color('--cream');
 let mode='ready',y=0,velocity=0,distance=0,obstacles:{x:number;h:number}[]=[],frame=0,prev=0,elapsed=0,spawn=1.8,raf=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const jump=()=>{if(reduced)return;if(mode!=='playing'){mode='playing';y=0;velocity=0;distance=0;obstacles=[];spawn=1.5;setStatus('playing')}else if(y<=0){velocity=550}};action.current=jump;
 const key=(e:KeyboardEvent)=>{if(!['Space','ArrowUp'].includes(e.code)||/INPUT|TEXTAREA|BUTTON/.test((e.target as HTMLElement).tagName))return;const r=c.getBoundingClientRect();if(r.bottom<0||r.top>window.innerHeight)return;e.preventDefault();jump()};window.addEventListener('keydown',key);
 function cloud(x:number,z:number){ctx.save();ctx.translate(x,z);ctx.fillStyle=cream;ctx.strokeStyle=ink;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,25);ctx.bezierCurveTo(-25,15,-10,-10,13,1);ctx.bezierCurveTo(20,-28,54,-22,59,1);ctx.bezierCurveTo(92,-10,100,31,75,31);ctx.lineTo(0,31);ctx.fill();ctx.stroke();ctx.restore()}
 function draw(time:number){const dt=Math.min((time-prev)/1000||0,.035);prev=time;elapsed+=dt;frame+=dt;
 if(mode==='playing'){distance+=dt*15;y+=velocity*dt;velocity-=1500*dt;if(y<0){y=0;velocity=0}spawn-=dt;if(spawn<=0){obstacles.push({x:940,h:35+Math.random()*18});spawn=1.65+Math.random()*.85}const speed=250+Math.min(distance,400)*.3;obstacles.forEach(o=>o.x-=speed*dt);obstacles=obstacles.filter(o=>o.x>-50);if(obstacles.some(o=>o.x<251&&o.x+30>205&&y<o.h-5)){mode='over';setStatus('over');setScore(Math.floor(distance))}if(Math.floor(distance)%5===0)setScore(Math.floor(distance))}
 ctx.clearRect(0,0,900,270);ctx.fillStyle=yellow;ctx.beginPath();ctx.arc(448,104,78,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ink;ctx.lineWidth=2;ctx.stroke();cloud(reduced?110:100+Math.sin(elapsed*.3)*25,50);cloud(reduced?650:650+Math.sin(elapsed*.2)*35,38);ctx.beginPath();ctx.moveTo(55,223);ctx.lineTo(845,223);ctx.stroke();ctx.fillStyle=ink;ctx.font='bold 14px sans-serif';ctx.fillText(`GOOD TIMES: ${Math.floor(distance).toString().padStart(4,'0')}`,650,205);
 const x=mode==='ready'?428:230;ctx.save();ctx.translate(x,210-y);const stride=reduced||mode==='over'?0:Math.sin(frame*(mode==='playing'?16:7))*16;ctx.strokeStyle=red;ctx.lineWidth=12;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-8,-8);ctx.lineTo(-14-stride,8);ctx.lineTo(-27-stride,8);ctx.moveTo(9,-8);ctx.lineTo(18+stride,8);ctx.lineTo(31+stride,8);ctx.stroke();ctx.strokeStyle=ink;ctx.lineWidth=2;ctx.fillStyle=navy;ctx.beginPath();ctx.ellipse(0,-32,24,31,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=navy;ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(-17,-44);ctx.lineTo(-35,-30+stride*.3);ctx.moveTo(18,-44);ctx.lineTo(35,-56-stride*.3);ctx.stroke();ctx.fillStyle=sky;ctx.strokeStyle=ink;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-76,34,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=ink;ctx.beginPath();ctx.arc(-12,-82,3,0,7);ctx.arc(12,-82,3,0,7);ctx.fill();ctx.beginPath();ctx.arc(0,-76,17,.2,Math.PI-.2);ctx.stroke();ctx.restore();
 obstacles.forEach(o=>{ctx.fillStyle=red;ctx.strokeStyle=ink;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(o.x,223-o.h,30,o.h,5);ctx.fill();ctx.stroke();ctx.fillStyle=cream;ctx.fillRect(o.x+6,228-o.h,18,4)});raf=requestAnimationFrame(draw)}
 raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',key)};
 },[]);
 return <div className="runner-wrap"><p className="runner-title">A little jump. A lot of good times.</p><canvas ref={canvas} width={900} height={270} onPointerDown={()=>action.current()} aria-label={`FIZZDAY jumping game. ${status==='over'?'Game over.':status} Score ${score}. Use space, up arrow, or tap to jump.`}/><Button variant="sticker" onClick={()=>action.current()}>{status==='over'?<RotateCcw/>:status==='ready'?<Play/>:<ArrowUp/>}{status==='over'?`Nice run! ${score} points · Play again`:status==='ready'?'Jump into the good times':'Space or tap to jump'}</Button></div>
}
