import {useState} from 'react';
import {Link} from '@tanstack/react-router';
import {ArrowLeft,ArrowRight,Plus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {flavors,benefits,type Flavor} from '@/lib/flavors';
import {Doodle} from './doodle';
import {RainbowHead} from './rainbow-head';
import {useCart} from './site-shell';
export function ProductCard({flavor,subscription=false}:{flavor:Flavor;subscription?:boolean}){const cart=useCart();return <article className="product-card"><Link to="/products/$flavor" params={{flavor:flavor.slug}} className={`product-art ${flavor.color}`}><img src={flavor.image} alt={`${flavor.name} FIZZDAY can`} width={350} height={650} loading="lazy"/></Link><Link to="/products/$flavor" params={{flavor:flavor.slug}}><h3>{flavor.name}</h3></Link><div className="product-meta"><span>Price to be confirmed</span>{subscription?<Button variant="sticker" onClick={()=>cart.add(flavor.slug,true)}>Subscribe</Button>:<Button variant="circle" aria-label={`Add ${flavor.name} to cart`} onClick={()=>cart.add(flavor.slug)}><Plus/></Button>}</div></article>}
export function ProductGrid({subscription=false,all=true}:{subscription?:boolean;all?:boolean}){return <div className="product-grid">{flavors.slice(0,all?5:4).map(f=><ProductCard key={f.slug} flavor={f} subscription={subscription}/>)}</div>}
export function Benefits(){const [active,setActive]=useState(0);const b=benefits[active];return <section className="section benefit-section"><div className="benefit-carousel"><Button variant="circle" aria-label="Previous benefit" onClick={()=>setActive((active+3)%4)}><ArrowLeft/></Button><article className={`benefit-card ${b.color}`} key={active}><h3 className="benefit-banner">{b.title}</h3><p>{b.text}</p><Doodle kind={b.icon}/></article><Button variant="circle" aria-label="Next benefit" onClick={()=>setActive((active+1)%4)}><ArrowRight/></Button></div><p className="benefit-pager">0{active+1} / 04 · LITTLE REASONS TO LOVE YOUR DAY</p></section>}
export function FlavorPanels(){const [start,setStart]=useState(0);const cart=useCart();return <div className="flavor-panels">{[0,1,2].map(n=>{const f=flavors[(start+n)%4];return <article className={`flavor-panel ${f.color}`} key={f.slug}><h3>{f.name}</h3><Link to="/products/$flavor" params={{flavor:f.slug}} aria-label={`Discover ${f.name}`}><img className="panel-can" src={f.image} alt={`${f.name} can`} loading="lazy" width={260} height={650}/></Link><Doodle kind={n===0?'smile':n===1?'sun':'flower'} className="panel-mascot"/><div className="panel-actions"><Button variant="sticker" asChild><Link to="/products/$flavor" params={{flavor:f.slug}}>Meet this flavor<ArrowRight/></Link></Button><Button variant="circle" aria-label={`Quick add ${f.name}`} onClick={()=>cart.add(f.slug)}><Plus/></Button></div></article>})}<Button variant="circle" className="panel-next" aria-label="Next flavors" onClick={()=>setStart((start+1)%4)}><ArrowRight/></Button></div>}
export function Marquee(){return <div className="marquee" aria-label="Good energy, great company, let the good times fizz"><div className="marquee-track" aria-hidden="true">{[0,1].map(i=><span key={i}>GOOD ENERGY ✦ GREAT COMPANY ✦ LET THE GOOD TIMES FIZZ ✦ GOOD ENERGY ✦ GREAT COMPANY ✦ LET THE GOOD TIMES FIZZ ✦</span>)}</div></div>}
export function Accordion({question,answer}:{question:string;answer:string}){return <details className="accordion"><summary>{question}<span className="plus"><Plus size={20}/></span></summary><p className="answer">{answer}</p></details>}
export function SubscribeCTA(){return <section className="subscription-cta"><RainbowHead text="NEVER RUN DRY" rainbow/><Doodle kind="flower" className="subscribe-flower"/><Doodle kind="rocket" className="subscribe-rocket"/><p>A fridge full of favorites. One less thing on your list. Meet the regulars club.</p><Button variant="coral" asChild><Link to="/pages/subscription">Make it a regular thing<ArrowRight/></Link></Button><small>*Space delivery? We’re working on our rocket license.</small></section>}
