import {createContext,useContext,useState,useEffect,type ReactNode} from 'react';
import {Link} from '@tanstack/react-router';
import {ChevronDown,ShoppingBag,UserRound,Menu,X,Minus,Plus,Trash2,Instagram,Music2,Facebook,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {flavors} from '@/lib/flavors';
import {Doodle} from './doodle';
import {RainbowHead} from './rainbow-head';
import {Runner} from './runner';
type CartItem={slug:string;quantity:number;subscription:boolean;size:string};
type CartValue={add:(slug:string,subscription?:boolean,quantity?:number,size?:string)=>void;open:()=>void};
const CartContext=createContext<CartValue>({add:()=>{},open:()=>{}});
export function useCart(){return useContext(CartContext)}
export function Wave({className='wave'}:{className?:string}){return <svg className={className} viewBox="0 0 1440 40" preserveAspectRatio="none" aria-hidden="true"><path d="M0 18C80 43 160-9 240 18S400 44 480 18S640-7 720 18S880 43 960 18S1120-7 1200 18S1360 43 1440 18V40H0Z"/></svg>}
export function SiteShell({children}:{children:ReactNode}){
 const [cart,setCart]=useState<CartItem[]>([]);const [drawer,setDrawer]=useState(false);const [announcement,setAnnouncement]=useState(true);const [scrolled,setScrolled]=useState(false);const [menu,setMenu]=useState(false);const [dropdown,setDropdown]=useState('');const [loader,setLoader]=useState(false);const [account,setAccount]=useState(false);
 useEffect(()=>{setAnnouncement(sessionStorage.getItem('fizzday-announcement')!=='closed');if(!sessionStorage.getItem('fizzday-loaded')&&!matchMedia('(prefers-reduced-motion: reduce)').matches){setLoader(true);sessionStorage.setItem('fizzday-loaded','yes');const id=setTimeout(()=>setLoader(false),2050);return()=>clearTimeout(id)}},[]);
 useEffect(()=>{const fn=()=>setScrolled(window.scrollY>40);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);
 useEffect(()=>{if(!drawer&&!menu&&!account)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setDrawer(false);setMenu(false);setAccount(false)}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',key)}},[drawer,menu,account]);
 const add=(slug:string,subscription=false,quantity=1,size='Pack size pending')=>{setCart(old=>{const found=old.find(x=>x.slug===slug&&x.subscription===subscription&&x.size===size);return found?old.map(x=>x===found?{...x,quantity:x.quantity+quantity}:x):[...old,{slug,quantity,subscription,size}]});setDrawer(true)};
 const count=cart.reduce((n,x)=>n+x.quantity,0);const closeMenu=()=>{setDropdown('');setMenu(false)};
 return <CartContext.Provider value={{add,open:()=>setDrawer(true)}}>
 {loader&&<div className="loader"><div className="wordmark">FIZZDAY</div><RainbowHead as="div" text="LET THE GOOD TIMES FIZZ" rainbow/></div>}
 {announcement&&<div className="announcement">A LITTLE FIZZ. A BIG DAY. ✦ MEET YOUR NEW FAVORITE TEA.<Button variant="ghost" size="icon" aria-label="Dismiss announcement" onClick={()=>{setAnnouncement(false);sessionStorage.setItem('fizzday-announcement','closed')}}><X size={16}/></Button></div>}
 <header className={`site-header ${scrolled?'scrolled':''}`}><div className="nav-inner"><Link to="/" aria-label="FIZZDAY home" className="wordmark" onClick={closeMenu}>{Array.from('FIZZDAY').map((l,i)=><span key={i}>{l}</span>)}<sup>®</sup></Link><nav className="nav-links" aria-label="Main navigation">
 <div className="nav-drop"><Button variant="nav" aria-expanded={dropdown==='shop'} onClick={()=>setDropdown(dropdown==='shop'?'':'shop')}>Shop<ChevronDown/></Button>{dropdown==='shop'&&<div className="drop-menu"><Link to="/collections/all" onClick={closeMenu}>All the good stuff</Link>{flavors.map(f=><Link key={f.slug} to="/products/$flavor" params={{flavor:f.slug}} onClick={closeMenu}>{f.name}</Link>)}</div>}</div>
 <div className="nav-drop"><Button variant="nav" aria-expanded={dropdown==='learn'} onClick={()=>setDropdown(dropdown==='learn'?'':'learn')}>Learn<ChevronDown/></Button>{dropdown==='learn'&&<div className="drop-menu"><Link to="/pages/story" onClick={closeMenu}>Our story</Link><Link to="/pages/stores" onClick={closeMenu}>Find your fizz</Link><Link to="/pages/faq" onClick={closeMenu}>Questions? Answers!</Link><Link to="/pages/contact" onClick={closeMenu}>Say hello</Link></div>}</div>
 <Button variant="nav" asChild className="subscription-nav"><Link to="/pages/subscription">Subscription</Link></Button><Button variant="nav" className="account-nav" aria-label="Account" onClick={()=>setAccount(true)}><UserRound/></Button><Button variant="nav" className="cart-toggle" aria-label={`Open cart, ${count} items`} onClick={()=>setDrawer(true)}><ShoppingBag/>{count>0&&<span className="cart-badge">{count}</span>}</Button><Button variant="nav" className="mobile-toggle" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></Button>
 </nav></div></header>
 <main>{children}</main>
 <footer className="footer"><Wave/><Runner/><div className="social-row"><Button variant="ghost" className="social-link" aria-label="Facebook link pending" title="Facebook link awaiting confirmation" disabled><Facebook/></Button><Button variant="ghost" className="social-link" aria-label="Instagram link pending" title="Instagram link awaiting confirmation" disabled><Instagram/></Button><Button variant="ghost" className="social-link" aria-label="TikTok link pending" title="TikTok link awaiting confirmation" disabled><Music2/></Button></div><div className="footer-bottom"><div className="footer-brand"><Link to="/" className="wordmark">FIZZDAY</Link><span>© 2026 FIZZDAY</span></div><nav><Link to="/pages/terms">Terms</Link><Link to="/pages/refund">Refund policy</Link><Link to="/pages/privacy">Privacy</Link><Link to="/pages/contact">Say hello</Link></nav></div></footer>
 {menu&&<div className="mobile-menu" role="dialog" aria-modal="true" aria-label="Navigation menu"><Button variant="circle" aria-label="Close menu" onClick={()=>setMenu(false)}><X/></Button><Link to="/collections/all" onClick={closeMenu}>SHOP THE FIZZ</Link><Link to="/pages/story" onClick={closeMenu}>OUR STORY</Link><Link to="/pages/subscription" onClick={closeMenu}>SUBSCRIPTION</Link><Link to="/pages/faq" onClick={closeMenu}>QUESTIONS?</Link><Link to="/pages/stores" onClick={closeMenu}>FIND US</Link><Link to="/pages/contact" onClick={closeMenu}>SAY HELLO</Link><Doodle kind="flower" className="w-28 self-end"/></div>}
 {account&&<div className="cart-overlay" onClick={()=>setAccount(false)}><div className="cart-drawer" role="dialog" aria-modal="true" aria-label="Your FIZZDAY account" onClick={e=>e.stopPropagation()}><div className="cart-heading"><h2>HEY, YOU!</h2><Button variant="circle" aria-label="Close account" onClick={()=>setAccount(false)}><X/></Button></div><div className="empty-cart"><Doodle kind="smile"/><p>Accounts will open when the shop launches. For now, find your favorite fizz.</p><Button variant="ink" asChild><Link to="/collections/all" onClick={()=>setAccount(false)}>Meet the crew<ArrowRight/></Link></Button></div></div></div>}
 {drawer&&<div className="cart-overlay" onClick={()=>setDrawer(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-label="Your cart" onClick={e=>e.stopPropagation()}><div className="cart-heading"><h2>YOUR FIZZ ({count})</h2><Button variant="circle" aria-label="Close cart" onClick={()=>setDrawer(false)}><X/></Button></div>{cart.length===0?<div className="empty-cart"><Doodle kind="smile"/><p>Your fridge called. It’s feeling lonely.</p><Button variant="coral" asChild><Link to="/collections/all" onClick={()=>setDrawer(false)}>Find your flavor<ArrowRight/></Link></Button></div>:<>{cart.map((item,index)=>{const f=flavors.find(f=>f.slug===item.slug);if(!f)return null;return <div className="cart-row" key={`${item.slug}-${index}`}><img src={f.image} width={140} height={400} alt={f.name}/><div><h3>{f.name}</h3><small>{item.subscription?'Subscription preference':'One-time purchase'} · {item.size}</small><div className="quantity"><Button variant="ghost" aria-label={`Decrease ${f.name} quantity`} onClick={()=>setCart(old=>old.map((x,i)=>i===index?{...x,quantity:Math.max(1,x.quantity-1)}:x))}><Minus/></Button><span>{item.quantity}</span><Button variant="ghost" aria-label={`Increase ${f.name} quantity`} onClick={()=>setCart(old=>old.map((x,i)=>i===index?{...x,quantity:x.quantity+1}:x))}><Plus/></Button></div><small>Price awaiting confirmation</small></div><Button variant="ghost" size="icon" aria-label={`Remove ${f.name}`} onClick={()=>setCart(old=>old.filter((_,i)=>i!==index))}><Trash2/></Button></div>})}<div className="cart-note"><p>Prices, pack sizes and delivery details are awaiting confirmation. Purchases aren’t open just yet.</p><Button variant="sage" disabled className="w-full">Checkout coming soon</Button></div></>}</aside></div>}
 </CartContext.Provider>
}
